# render.yaml
services:
  - type: web
    name: ci-cd-demo-app
    env: docker
    plan: free
    repo: https://github.com/DajNJ/CI-CD-Pipeline-
    region: oregon  # or frankfurt, singapore, etc.
    branch: main
    autoDeploy: true
    dockerfilePath: ./Dockerfile
    dockerContext: ./
    envVars:
      - key: NODE_ENV
        value: production
      # - key: DATABASE_URL
      #   value: your_database_connection_string
    healthCheckPath: /health
