version: 2.1

executors:
  docker-executor:
    docker:
      - image: cimg/base:stable

jobs:
  build-and-push:
    executor: docker-executor
    steps:
      - checkout

      - setup_remote_docker:
          docker_layer_caching: true

      - run:
          name: Build Docker Image
          command: |
            docker build -t $DOCKERHUB_USERNAME/nginx .

      - run:
          name: Log in to Docker Hub
          command: |
            echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin

      - run:
          name: Push Docker Image
          command: |
            docker push $DOCKERHUB_USERNAME/nginx

  test-node:
    docker:
      - image: cimg/node:current
    steps:
      - checkout
      - run:
          name: Run Node Tests
          command: npm test

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - test-node
      - build-and-push