version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout

      - setup_remote_docker:
          docker_layer_caching: true

      - run:
          name: Log in to Docker Hub
          command: |
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USER" --password-stdin

      - run:
          name: Build Docker image
          command: |
            docker build -t $DOCKERHUB_USER/demo-app .

      - persist_to_workspace:
          root: .
          paths:
            - .

  test:
    docker:
      - image: cimg/base:stable
    steps:
      - attach_workspace:
          at: .

      - setup_remote_docker:
          docker_layer_caching: true

      - run:
          name: Run Container for Testing
          command: |
            docker run -d -p 80:3000 --name test-app $DOCKERHUB_USER/demo-app
            sleep 10
            CONTAINER_IP=$(docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' test-app)
            curl --fail http://$CONTAINER_IP:3000/health || (docker logs test-app && exit 1)

      - run:
          name: Clean Up Container
          command: |
            docker stop test-app && docker rm test-app

  deploy:
    docker:
      - image: cimg/python:3.9
    steps:
      - attach_workspace:
          at: .

      - setup_remote_docker:
          docker_layer_caching: true

      - run:
          name: Install AWS CLI
          command: |
            pip install awscli

      - run:
          name: Log in to Docker Hub
          command: |
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USER" --password-stdin

      - run:
          name: Push Docker Image
          command: |
            docker push $DOCKERHUB_USER/demo-app

      - add_ssh_keys:
          fingerprints:
            - "$SSH_KEY_FINGERPRINT"

      - run:
          name: Setup SSH
          command: |
            mkdir -p ~/.ssh
            echo "Host *" >> ~/.ssh/config
            echo "  StrictHostKeyChecking no" >> ~/.ssh/config
            echo "  UserKnownHostsFile /dev/null" >> ~/.ssh/config
            chmod 600 ~/.ssh/config

      - run:
          name: Deploy to EC2
          command: |
            ssh ec2-user@$EC2_HOST '\<<' 'EOF'
              # Install Docker if not present
              if ! command -v docker &> /dev/null; then
                sudo yum update -y
                sudo yum install -y docker
                sudo systemctl start docker
                sudo systemctl enable docker
                sudo usermod -a -G docker ec2-user
              fi
              
              # Deploy application
              docker pull '$DOCKERHUB_USER'/demo-app
              docker stop demo-app 2>/dev/null || true
              docker rm demo-app 2>/dev/null || true
              docker run -d -p 80:3000 --name demo-app '$DOCKERHUB_USER'/demo-app
              
              # Verify deployment
              sleep 5
              docker ps
              curl -f http://localhost:80/health || echo "Health check failed"
            EOF

workflows:
  version: 2
  build_test_deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - test
